### ISSUE TITLE
Data for the project

### ISSUE THREAD

**Issue by sean-metzger** [saraivaufc/instance-segmentation-maskrcnn#1]
This project looks great! Where can i get the data used for train/test?

**Comment by robmarkcole** [comment]
It is here, but it's not clear the annotation format - Roboflow doesn't auto recognise it

https://www.kaggle.com/datasets/saraivaufc/center-pivot-irrigation-systems

**Comment by saraivaufc** [comment]
Hi @robmarkcole. I used this script to create the training and validation datasets: https://github.com/saraivaufc/build-encoded-pixels-from-raster-vector/blob/master/2_build_encoded_pixels.py
